# Generated by Django 3.1.7 on 2021-03-19 04:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('archive', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('roomcode', models.CharField(max_length=4, unique=True)),
                ('archive', models.BooleanField(default=False)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initiativeTrackerApi.campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('challengeRating', models.FloatField()),
                ('AC', models.IntegerField()),
                ('maxHP', models.IntegerField()),
                ('initiativeBonus', models.IntegerField(default=0)),
                ('monsterType', models.CharField(max_length=50)),
                ('damageResistance', models.TextField(default='none')),
                ('damageImmunity', models.TextField(default='none')),
                ('conditionImmunity', models.TextField(default='none')),
                ('speed', models.CharField(max_length=50)),
                ('spellcaster', models.BooleanField(default=False)),
                ('strengthStat', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('dexterityStat', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('constitutionStat', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('intelligenceStat', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('wisdomStat', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('charismaStat', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('strength_savingthrow', models.IntegerField(default=0)),
                ('dexterity_savingthrow', models.IntegerField(default=0)),
                ('constitution_savingthrow', models.IntegerField(default=0)),
                ('intelligence_savingthrow', models.IntegerField(default=0)),
                ('wisdom_savingthrow', models.IntegerField(default=0)),
                ('charisma_savingthrow', models.IntegerField(default=0)),
                ('size', models.CharField(default='Medium', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'monster',
                'verbose_name_plural': 'monsters',
            },
        ),
        migrations.CreateModel(
            name='PlayerCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('AC', models.IntegerField()),
                ('maxHP', models.IntegerField()),
                ('initiativeBonus', models.IntegerField()),
                ('strengthStat', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('dexterityStat', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('constitutionStat', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('intelligenceStat', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('wisdomStat', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('charismaStat', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('speed', models.CharField(max_length=50)),
                ('alive', models.BooleanField(default=True)),
                ('characterClass', models.CharField(choices=[('Barbarian', 'Barbarian'), ('Bard', 'Bard'), ('Cleric', 'Cleric'), ('Druid', 'Druid'), ('Fighter', 'Fighter'), ('Monk', 'Monk'), ('Paladin', 'Paladin'), ('Ranger', 'Ranger'), ('Rogue', 'Rogue'), ('Sorcerer', 'Sorcerer'), ('Warlock', 'Warlock'), ('Wizard', 'Wizard')], default=None, max_length=9)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initiativeTrackerApi.campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'player character',
                'verbose_name_plural': 'player characters',
            },
        ),
        migrations.CreateModel(
            name='Playerencounterpair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiative', models.IntegerField()),
                ('concentration', models.BooleanField(default=False)),
                ('temporaryHealth', models.IntegerField(default=0)),
                ('currentHealth', models.IntegerField(null=True)),
                ('characterId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initiativeTrackerApi.playercharacter')),
                ('encounterId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initiativeTrackerApi.encounter')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Monsterencounterpair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiative', models.IntegerField()),
                ('currentHealth', models.IntegerField()),
                ('concentration', models.BooleanField(default=False)),
                ('temporaryHealth', models.IntegerField(default=0)),
                ('encounterId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='initiativeTrackerApi.encounter')),
                ('monsterId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initiativeTrackerApi.monster')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
