# Generated by Django 3.1.7 on 2021-03-13 16:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('challengeRating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('AC', models.IntegerField()),
                ('maxHP', models.IntegerField()),
                ('initiativeBonus', models.IntegerField()),
                ('monsterType', models.CharField(max_length=50)),
                ('damageResistance', models.TextField(default='none')),
                ('damageImmunity', models.TextField(default='none')),
                ('conditionImmunity', models.TextField(default='none')),
                ('speed', models.CharField(max_length=50)),
                ('spellcaster', models.BooleanField(default=False)),
                ('strengthStat', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('dexterityStat', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('constitutionStat', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('intelligenceStat', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('wisdomStat', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('charismaStat', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('strength_savingthrow', models.IntegerField(default=0)),
                ('dexterity_savingthrow', models.IntegerField(default=0)),
                ('constitution_savingthrow', models.IntegerField(default=0)),
                ('intelligence_savingthrow', models.IntegerField(default=0)),
                ('wisdom_savingthrow', models.IntegerField(default=0)),
                ('charisma_savingthrow', models.IntegerField(default=0)),
                ('size', models.CharField(choices=[('T', 'tiny'), ('S', 'small'), ('M', 'medium'), ('L', 'large'), ('H', 'huge'), ('G', 'gargantuan')], default='M', max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'monster',
                'verbose_name_plural': 'monsters',
            },
        ),
        migrations.CreateModel(
            name='PlayerCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('AC', models.IntegerField()),
                ('maxHP', models.IntegerField()),
                ('initiativeBonus', models.IntegerField()),
                ('strengthStat', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('dexterityStat', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('constitutionStat', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('intelligenceStat', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('wisdomStat', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('charismaStat', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('speed', models.CharField(max_length=50)),
                ('alive', models.BooleanField(default=True)),
                ('characterClass', models.CharField(choices=[('bab', 'Barbarian'), ('bad', 'Bard'), ('cle', 'Cleric'), ('dru', 'Druid'), ('fig', 'Fighter'), ('mon', 'Monk'), ('pal', 'Paladin'), ('ran', 'Ranger'), ('rog', 'Rogue'), ('sor', 'Sorcerer'), ('war', 'Warlock'), ('wiz', 'Wizard')], default=None, max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'player character',
                'verbose_name_plural': 'player characters',
            },
        ),
        migrations.CreateModel(
            name='Playerencounterpair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiative', models.IntegerField()),
                ('concentration', models.BooleanField(default=False)),
                ('temporaryHealth', models.IntegerField(default=0)),
                ('currentHealth', models.IntegerField(null=True)),
                ('characterId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initiativeTrackerApi.playercharacter')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Monsterencounterpair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiative', models.IntegerField()),
                ('currentHealth', models.IntegerField(null=True)),
                ('concentration', models.BooleanField(default=False)),
                ('temporaryHealth', models.IntegerField(default=0)),
                ('monsterId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initiativeTrackerApi.monster')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('roomcode', models.CharField(max_length=4)),
                ('archive', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
