# Generated by Django 3.1.7 on 2021-03-15 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiativeTrackerApi', '0002_auto_20210313_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='size',
            field=models.CharField(choices=[('tiny', 'tiny'), ('small', 'small'), ('medium', 'medium'), ('large', 'large'), ('huge', 'huge'), ('gargantuan', 'gargantuan')], default='M', max_length=10),
        ),
    ]
