# Generated by Django 3.1.7 on 2021-03-04 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initiativeTrackerApi', '0002_encounterpair'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monster',
            options={'verbose_name': 'monster', 'verbose_name_plural': 'monsters'},
        ),
        migrations.AlterModelOptions(
            name='playercharacter',
            options={'verbose_name': 'player character', 'verbose_name_plural': 'player characters'},
        ),
        migrations.AddField(
            model_name='encounterpair',
            name='monsterId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='initiativeTrackerApi.monster'),
        ),
        migrations.AlterField(
            model_name='encounterpair',
            name='characterId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='initiativeTrackerApi.playercharacter'),
        ),
    ]
