# Generated by Django 3.1.7 on 2021-03-18 00:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('initiativeTrackerApi', '0004_auto_20210316_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='roomcode',
            field=models.CharField(max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
