# Generated by Django 3.1.7 on 2021-03-06 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('initiativeTrackerApi', '0006_auto_20210306_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
