# Generated by Django 3.1.7 on 2021-03-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiativeTrackerApi', '0007_auto_20210306_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='strength_savingthrow',
            field=models.IntegerField(default=0),
        ),
    ]
