# Generated by Django 3.1.7 on 2021-03-09 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initiativeTrackerApi', '0008_auto_20210306_1827'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Encounterpair',
        ),
    ]
