# Generated by Django 3.1.7 on 2021-03-09 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('initiativeTrackerApi', '0009_delete_encounterpair'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playerencounterpair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiative', models.IntegerField()),
                ('concentration', models.BooleanField(default=False)),
                ('temporaryHealth', models.IntegerField(default=0)),
                ('currentHealth', models.IntegerField()),
                ('characterId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initiativeTrackerApi.playercharacter')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Monsterencounterpair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiative', models.IntegerField()),
                ('currentHealth', models.IntegerField()),
                ('concentration', models.BooleanField(default=False)),
                ('temporaryHealth', models.IntegerField()),
                ('monsterId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initiativeTrackerApi.monster')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
