# Generated by Django 3.1.7 on 2021-03-09 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiativeTrackerApi', '0010_monsterencounterpair_playerencounterpair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerencounterpair',
            name='currentHealth',
            field=models.IntegerField(null=True),
        ),
    ]
